services:

  backend:
    build: ./backend
    container_name: nal-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: nal-frontend
    ports:
      - "5173:5173"